name: Test build Pull Request

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]


permissions:
  id-token: write   # Required for OIDC auth
  contents: read    # Required to read repo contents
  
env:
  IGNORE_PATTERN: (^README\.md$|^.gitignore|^.vscode/)

jobs:
  test-build:
    name: Test build
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # fetch full history

      - name: Detect code changes excluding README/docs
        id: check_changes
        run: |
          PR_BASE="${{ github.event.pull_request.base.sha }}"
          PR_HEAD="${{ github.event.pull_request.head.sha }}"

          echo "PR base: $PR_BASE"
          echo "PR head: $PR_HEAD"
          
          # Get list of changed files in the PR
          CHANGED_FILES=$(git diff --name-only $PR_BASE $PR_HEAD})
          echo "Changed Files: "
          echo $CHANGED_FILES
          echo " "

          # Filter out files to ignore (README.md, docs/**)
          CODE_CHANGED=$(echo "$CHANGED_FILES" | grep -vE '${{ env.IGNORE_PATTERN }}')

          # Output whether code changed
          if [ -z "$CODE_CHANGED" ]; then
            echo "No relevant code changes"
            echo "code_changed=false" >> $GITHUB_ENV
          else
            echo "Code changes detected:"
            echo "$CODE_CHANGED"
            echo "code_changed=true" >> $GITHUB_ENV
          fi

      - name: Test-Build
        if: env.code_changed == 'true'
        id: build
        run: |
          npm i
          npm run build
